branch-defaults:
  default:
    environment: null
global:
  application_name: OctClf
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
